name: PR Security Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Semgrep PR scan
    - name: Semgrep PR Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "auto"
        audit_on: "pull_request"

    # TruffleHog PR secret scan
    - name: TruffleHog PR Secret Scan
      uses: trufflesecurity/trufflehog@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        base: ${{ github.event.pull_request.base.sha }}
        head: ${{ github.event.pull_request.head.sha }}
